export const data: any = {
    "2zd33b8c": {
        name: "Naruto",
        last: "Uzumaki",
        id: "2zd33b8c",
        sku: "NUR72KCM",
        image: "/naruto.jpg",
        aldea: "Aldea Oculta de la Hoja",
        nacimiento: "10 de octubre",
        clan: "Uzumaki",
        habilidad: [
            "Detección de Sentimientos Negativos, ",
            "Habilidad para Flotar, ",
            "Habilidad de Regeneración",
        ],
        logo: "/b.png",
    },
    "6trfgkkj": {
        name: "Sakura",
        last: "Haruno",
        id: "6trfgkkj",
        sku: "AX4M8SJV",
        image: "/Sakura_Haruno.png",
        aldea: "Aldea Oculta de la Hoja",
        nacimiento: "28 de marzo",
        clan: "Uchiha",
        habilidad: [
            "Ninjutsu médico, ",
            "Transformación de la Naturaleza, ",
            "Fūinjutsu",
        ],
        logo: "/b.png",
    },
    "7bcr49em": {
        name: "Sasuke",
        last: "Uchiha",
        id: "7bcr49em",
        sku: "HYA78F6J",
        image: "/sasuke.jpg",
        aldea: "Aldea Oculta de la Hoja",
        nacimiento: "23 de julio",
        clan: "Uchiha",
        habilidad: [
            "Control de chakra, ",
            "Shurikenjutsu, ",
            "Dōjutsu",
        ],
        logo: "/b.png",
    },
    "098323ks": {
        name: "Hinata",
        last: "Hyuga",
        id: "098323ks",
        sku: "BXD100BLK",
        image: "/Hinata.png",
        aldea: "Aldea Oculta de la Hoja",
        nacimiento: "27 de diciembre",
        clan: "Hyūga | Uzumaki",
        habilidad: [
            "Control de chakra, ",
            "Taijutsu, ",
            "Ninjutsu",
        ],
        logo: "/b.png",
    },
    b8uthe2y: {
        name: "Gaara",
        last: "del desierto",
        id: "b8uthe2y",
        sku: "RMRCZN7E",
        image: "/Gaara.png",
        aldea: "Aldea Oculta de la Arena",
        nacimiento: "19 de enero",
        clan: "Kazekage",
        habilidad: [
            "Fūinjutsu, ",
            "Bukijutsu, ",
            "Ninjutsu",
        ],
        logo: "/arena.png",
    },
    ewxsd6xb: {
        name: "Rock",
        last: "Lee",
        id: "ewxsd6xb",
        sku: "N55229ZA",
        image: "/rocklee.png",
        aldea: "Aldea Oculta de la Hoja",
        nacimiento: "27 de noviembre",
        clan: "Lee",
        habilidad: [
            "Taijutsu",
        ],
        logo: "/b.png",
    },
    fpr72m9k: {
        name: "Temari",
        last: "?",
        id: "fpr72m9k",
        sku: "B4HZ42TM",
        image: "/temari.jpg",
        aldea: "Aldea Oculta de la Arena",
        nacimiento: "23 de agosto",
        clan: "Clan Kazekage | Clan Nara",
        habilidad: [
            "Tessenjutsu y Transformación de la Naturaleza, ",
            "Jutsu de Invocación"
        ],
        logo: "/arena.png",
    },
    t9dv25gs: {
        name: "Shikamaru",
        last: "Nara",
        id: "t9dv25gs",
        sku: "ZY3T9XXC",
        image: "/shikamaru.jpg",
        aldea: "Aldea Oculta de la Hoja",
        nacimiento: "23 de septiembre",
        clan: "Clan Nara",
        habilidad: [
            "Inteligencia, ",
            "Jutsus de Sombra"
        ],
        logo: "/b.png",
    },
    t345w48y: {
        name: "Neji",
        last: "Hyuga",
        id: "t345w48y",
        sku: "MW79ZZ6Y",
        image: "/neji.png",
        aldea: "Aldea Oculta de la Hoja",
        nacimiento: "3 de julio",
        clan: "Clan Hyūga",
        habilidad: [
            "Control de Chakra, ",
            "Dōjutsu, ",
            "Taijutsu"
        ],
        logo: "/b.png",
    },
    t945v48i: {
        name: "Kiba",
        last: "Inozuka",
        id: "t945v48i",
        sku: "MW79ZZ6Y",
        image: "/kiba.jpg",
        aldea: "Aldea Oculta de la Hoja",
        nacimiento: "7 de julio",
        clan: "Clan Inuzuka",
        habilidad: [
            "Velocidad, ",
            "Habilidad con los Sentidos",
        ],
        logo: "/b.png",
    },
    tj45y48l: {
        name: "Choji",
        last: "Akimichi",
        id: "tj45y48l",
        sku: "MW79ZZ6Y",
        image: "/choji.png",
        aldea: "Aldea Oculta de la Hoja",
        nacimiento: "1 de mayo",
        clan: "Clan Akimichi",
        habilidad: [
            "Taijutsu",
        ],
        logo: "/b.png",
    },
    t74oy48u: {
        name: "Kankuro",
        last: "?",
        id: "t74oy48u",
        sku: "MW79ZZ6Y",
        image: "/kankuro.png",
        aldea: "Aldea Oculta de la Arena",
        nacimiento: "15 de mayo",
        clan: "Clan Kazekage",
        habilidad: [
            "Maestro Marionetista",
        ],
        logo: "/arena.png",
    },
};

export default data;
